config/routes.rb
Test::Application.routes.draw do
  get "users/index"

  get '/invite' => "admins#invite", as: :invite_writer
  post '/invite' => "admins#welcome"
  resources :writers
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  root :to => redirect("/login")
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :user_attributes
  
  has_one :user, :as => :role, :dependent => :destroy
  
  accepts_nested_attributes_for :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable

  attr_accessible :email, :password, :password_confirmation
  
  belongs_to :role, polymorphic: true
  
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, uniqueness: true
  validates :password, presence: true
end

app/models/writer.rb
class Writer < ActiveRecord::Base
  attr_accessible :first_name, :gender, :last_name, :screen_name, :user_attributes
  
  has_one :user, :as => :role, :dependent => :destroy
  
  accepts_nested_attributes_for :user
  
  validates :first_name, :last_name, :screen_name, :gender , presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_filter :authenticate_user!, :check_role
  
  def invite
    @user = User.new
  end
  
  def welcome
    @user = User.new(params[:user])
    redirect_to invite_writer_path, notice: "Email Id is invalid." and return if ( params[:user][:email].blank? ||  (params[:user][:email] =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i) != 0 )
    AdminMailer.invite(@user).deliver
    redirect_to invite_writer_path, notice: "Mail successfully send."
  end
  
  def check_role
    redirect_to Writer.find(current_user.role_id), notice: "You don't have access to this page." if current_user.role_type == "Writer"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def after_sign_in_path_for(resource)
    current_user.role_type == "Admin" ? invite_writer_path : Writer.find(current_user.role_id)
  end
  
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  before_filter :authenticate_user!, except: [:new, :create, :show]
  before_filter :check_role, only: [:index, :destroy, :edit, :update]
  
  def new
    @writer = Writer.new
    @writer.build_user
  end
  
  def create
    @writer = Writer.new(params[:writer])
    render "new" and return if @writer.invalid?
    @writer.save
    redirect_to @writer, notice: "Writer successfully added."
  end
  
  def show
    unless current_user.nil?
      redirect_to Writer.find(current_user.role_id), notice: "You don't have access to this Page." and return if ( params[:id] != current_user.role_id.to_s && current_user.role_type == "Writer" )
    end
    @writer = Writer.find params[:id]
  end
  
  def index
    @writers = Writer.all
  end
  
  def edit
    @writer = Writer.find params[:id]
  end
  
  def update
    @writer = Writer.find params[:id]
    @writer.update_attributes(params[:writer])
    render "edit" and return if @writer.invalid?
    redirect_to @writer, notice: "Writer successfully updated"
  end
  
  def destroy
    Writer.destroy params[:id]
    redirect_to writers_path, notice: "Writer successfully deleted"
  end
  
  private
  
  def check_role
    redirect_to Writer.find(current_user.role_id), notice: "You don't have access to this page." if current_user.role_type == "Writer"
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/admins/invite.html.erb
<label>Please enter email to invite Writer</label>
<%= form_for(@user, url: { action: "welcome"}, html: { class: "form-horizontal"}) do |f| %>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Invite Writer", class: "btn btn-default" %>
    </div>
  </div>
 
<% end  %>

app/views/common/_navigation.html.erb
<div>
<% if user_signed_in? %>
  Welcome <strong><%= current_user.email %></strong>
  <%= link_to "Writers List", writers_path %>
  <%= link_to "Invite Writer", invite_writer_path %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% end %>
</div>
<% if flash[:notice] %>
  <div class="alert alert-info">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: '/common/navigation' %>
<%= yield %>

</body>
</html>

app/views/writers/_form.html.erb
<%= form_for(@writer) do |f| %>
  <% if @writer.errors.any? %>
    <div class="alert alert-warning">
      <ul>
      <% @writer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :first_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :first_name %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_field :last_name %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :screen_name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_field :screen_name %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :gender, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_field :gender %>
    </div>
  </div>
  <%= f.fields_for :user do |rf| %>
    <div class="form-group">
      <%= rf.label :email, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
      <%= rf.text_field :email %>
      </div>
    </div>
    <div class="form-group">
      <%= rf.label :password, class: "col-sm-2 control-label" %>
      <div class="col-sm-10">
      <%= rf.password_field :password %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Submit", class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/writers/edit.html.erb
<h3>Edit Writer</h3>

<%= render 'form' %>

app/views/writers/index.html.erb
<h3 >Listing Writers</h3>
<table class="table table-condensed">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Screen Name</th>
    <th>Gender</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @writers.each do |writer| %>
  <tr>
    <td><%= writer.first_name %></td>
    <td><%= writer.last_name %></td>
    <td><%= writer.screen_name %></td>
    <td><%= writer.gender %></td>
    <td><%= writer.user.email %></td>
    <td><%= link_to 'Show', writer %></td>
    <td><%= link_to 'Edit', edit_writer_path(writer) %></td>
    <td><%= link_to 'Delete', writer, method: :delete %></td>
  </tr>
<% end %>
</table>
<%= link_to 'New Writer', new_writer_path %>

app/views/writers/new.html.erb
<h3>New Writer</h3>

<%= render 'form' %>

app/views/writers/show.html.erb
<p>
  <label>First Name:</label>
  <%= @writer.first_name %>
</p>

<p>
  <label>Last Name:</label>
  <%= @writer.last_name %>
</p>

<p>
  <label>Screen Name:</label>
  <%= @writer.screen_name %>
</p>

<p>
  <label>Gender:</label>
  <%= @writer.gender %>
</p>

<p>
  <label>Email:</label>
  <%= @writer.user.email %>
</p>
<% if current_user.nil? %>
  <%= link_to 'Sign in', new_user_session_path %>
<% end %>